controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
# config/routes.yaml

about:
    resource: ../src/Controller/PageController.php
    type: annotation

redirect:
    resource: ../src/Controller/PageController.php
    type: annotation